import { CheckCircle2, Clock3, Factory, PackageCheck } from 'lucide-react'
import Link from 'next/link'
import type { DashboardSummary, Production } from '@/types'
import KpiCard from '@/components/dashboard/ui/KpiCard'
import { cardBase } from '@/lib/dashboard/design'

export default function OperatorDashboard({ summary, productions, firstName }: { summary: DashboardSummary | null; productions: Production[]; firstName: string }) {
  const active = productions.filter(item => item.status === 'en_cours')
  const completed = productions.filter(item => item.status === 'terminee')
  const planned = productions.filter(item => item.status === 'planifiee')
  const quantity = productions.reduce((sum, item) => sum + Number(item.quantity || 0), 0)
  return <div className="space-y-5">
    <div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-[10px] font-bold uppercase tracking-widest text-blue-600">Espace opérateur</p><h1 className="mt-1 text-2xl font-bold text-[#0b1e3b]">Bonjour {firstName}</h1><p className="mt-1 text-sm text-slate-500">Suivez vos lots affectés et enregistrez les opérations de production.</p></div><Link href="/dashboard/lots" className="inline-flex rounded-md bg-[#102544] px-4 py-2.5 text-sm font-bold text-white">Ouvrir mes lots</Link></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><KpiCard label="Mes lots en cours" value={String(active.length)} icon={Factory} accent="amber" /><KpiCard label="Quantité affectée" value={`${quantity.toLocaleString('fr-FR')} unités`} icon={PackageCheck} accent="indigo" /><KpiCard label="Lots terminés" value={String(completed.length)} icon={CheckCircle2} accent="emerald" /><KpiCard label="Lots planifiés" value={String(planned.length)} icon={Clock3} accent="slate" /></div>
    <section className={`${cardBase} overflow-hidden`}><div className="border-b px-5 py-4"><h2 className="font-bold text-slate-900">Mes dernières productions</h2><p className="mt-1 text-xs text-slate-500">Seuls les lots qui vous sont affectés sont affichés.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead className="bg-slate-50 text-[10px] font-bold uppercase tracking-wider text-slate-400"><tr><th className="p-4">Référence</th><th>Produit</th><th>Quantité</th><th>Statut</th><th>Date</th></tr></thead><tbody className="divide-y">{productions.slice(0, 8).map(item => <tr key={item.id}><td className="p-4 font-mono font-semibold">{item.reference}</td><td>{item.product?.name || `Produit ${item.product_id}`}</td><td>{Number(item.quantity).toLocaleString('fr-FR')} unités</td><td><span className="rounded-md border bg-slate-50 px-2 py-1 text-xs">{item.status.replace('_', ' ')}</span></td><td>{new Date(item.created_at).toLocaleDateString('fr-FR')}</td></tr>)}{!productions.length && <tr><td colSpan={5} className="p-12 text-center text-slate-400">Aucun lot ne vous est encore affecté.</td></tr>}</tbody></table></div></section>
    <section className="grid gap-4 md:grid-cols-2"><div className={`${cardBase} p-5`}><h2 className="font-bold">État de mes productions</h2><div className="mt-4 space-y-3">{(summary?.production_status || []).map(item => <div key={item.name} className="flex items-center justify-between border-b border-slate-100 pb-2 text-sm"><span className="text-slate-600">{item.name}</span><strong>{item.value}</strong></div>)}</div></div><div className={`${cardBase} p-5`}><h2 className="font-bold">Actions autorisées</h2><div className="mt-4 grid gap-2"><Link href="/dashboard/operations" className="rounded-md border p-3 text-sm font-semibold hover:bg-slate-50">Lancer une opération industrielle</Link><Link href="/dashboard/lots" className="rounded-md border p-3 text-sm font-semibold hover:bg-slate-50">Consulter ou clôturer mes lots</Link><Link href="/dashboard/profil" className="rounded-md border p-3 text-sm font-semibold hover:bg-slate-50">Consulter mon profil</Link></div></div></section>
  </div>
}
